version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - "cloudsql-proxy"
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - AUTH_SECRET_KEY=${AUTH_SECRET_KEY}
      - AUTH_ISSUER=${AUTH_ISSUER}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
  cloudsql-proxy:
      container_name: cloudsql-proxy
      image: gcr.io/cloudsql-docker/gce-proxy:1.19.1
      command: /cloud_sql_proxy --dir=/cloudsql -instances=<INSTANCE_CONNECTION_NAME>=tcp:0.0.0.0:5432 -credential_file=/secrets/cloudsql/credentials.json
      ports:
        - 5432:5432
      volumes:
        - ./credentials.json:/secrets/cloudsql/credentials.json
      restart: always
  db:
    image: "postgres:14.2-alpine"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
